// Generated by MARIGOLD-BATCH-APP (5-field outreach batch).
import type { MarigoldConfig } from "./config";

export const BUSINESS: MarigoldConfig = {
  "businessName": "Cappuccino",
  "location": "",
  "palette": "marigold-green",
  "fontSet": "fraunces-dmsans",
  "heroImage": "C:\\Users\\steve\\Downloads\\cafe-heros\\cappucino-edin.jpg",
  "aboutQuote": "We opened Cappuccino to be the kind of place we missed — somewhere warm, where the bread is real, the coffee is strong and nobody is in a rush.",
  "aboutAttribution": "— The owners",
  "phone": "07427 694040",
  "email": "cappuccinoedinburgh@gmail.com",
  "address": [
    "25 Jeffrey Street",
    "Edinburgh"
  ]
};
